### ISSUE TITLE
现在是不是用不了了?

### ISSUE THREAD

**Issue by shaoting0730** [kkkelicheng/ReactNative-CountDownButton#1]
![image](https://user-images.githubusercontent.com/14305431/40957664-b3291cf0-68c8-11e8-857b-55433ea6ea43.png)

**Comment by kkkelicheng** [comment]
可以用吧
我这个能支持版本很低的呢.
高版本也一定能用的.

**Comment by shaoting0730** [comment]
我把PropsTypes删了就OK了
