### ISSUE TITLE
设计上有严重的漏洞。

### ISSUE THREAD

**Issue by smallgirl** [kkkelicheng/ReactNative-CountDownButton#2]
Date.now()  受系统时间的影响，如果用户手动改了系统时间，那么你这计算器就会错乱，android 的api中SystemClock.elapsedRealtime可以获取开机系统运行的时间，不受系统时间影响。我的是现实是封装原生的api来通知js端口。同样的ios也有类似的api。

**Comment by kkkelicheng** [comment]
>  如果用户手动改了系统时间

这个是会的,你说的没错.


嗯, 你的方案. 我仔细思考了一下,确实是更好的方案.
但是这个框架仅仅是轻量级的,无侵入原生.能满足一般的需求.

谢谢你的指点.
